### PR TITLE
Remove completed boolean

### PR DESCRIPTION
**Pull request by robertdanci**
Hi,

Is there any reason for the complete flag?

It seemed to me superfluous so I deleted it. The tests pass fine. 

Let me know what you think.

Regards,
Robert

### CODE REVIEW

**Comment by jmnarloch** [comment]
So my guess is that I introduced the completed flag originally for covering the edge cases like actual completion, error or timeout, though I know that DeferredResult has the check to prevent from setting more the one value, though it uses explicit lock to do that.

At the moment I'm not sure if I want to remove the flag or not, both version seems to be correct at this point.

**Comment by robertdanci** [comment]
Some reasons to remove it:

1. All unnecessary code should be removed as it creates confusion. Either we should write a test to prove the code is needed or remove it.
2. In both instances DeferredResultSubscriber#onNext is used, it will only be called once: in SingleDeferredResult it is clear, in ObservableDeferredResult only once because you use observable.toList() which says in the documentation 
> Returns an Observable that emits a single item, a list composed of all the items emitted by the source

**Comment by jmnarloch** [comment]
There one possible edge case to add in general: the illy implemented Subscriber, that calls the onComplete method before executing onNext, though this probably might not happen in current scenario.

**Comment by jmnarloch** [comment]
Merged through https://github.com/jmnarloch/rxjava-spring-boot-starter/commit/1125a8e21c9a1c5e51e0c9de354dae52a6b488c3 
Thanks!

**Pull request closed without merging**
